
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package soliditycompiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Res_Moddifier = 48;
  public static final int Res_Uint256 = 69;
  public static final int Multiplique = 110;
  public static final int Res_Bytes16 = 21;
  public static final int Res_Uint8 = 64;
  public static final int Coma = 121;
  public static final int CierraLlave = 115;
  public static final int Res_Constructor = 35;
  public static final int CorrerALaIzquierda = 99;
  public static final int Res_Uint64 = 67;
  public static final int Res_Uint4 = 63;
  public static final int Res_Uint2 = 62;
  public static final int Trans_Callcode = 75;
  public static final int Trans_Call = 74;
  public static final int MenorQue = 101;
  public static final int Res_For = 42;
  public static final int Porcentaje = 107;
  public static final int Trans_Send = 77;
  public static final int Res_Bytes128 = 24;
  public static final int Res_Enum = 40;
  public static final int Punto = 122;
  public static final int Res_Struct = 57;
  public static final int Res_Int128 = 9;
  public static final int Res_Do = 39;
  public static final int Unit_Days = 79;
  public static final int Unit_Hours = 82;
  public static final int Res_Int16 = 6;
  public static final int Trans_Balance = 73;
  public static final int Res_Int = 2;
  public static final int Cientifico = 90;
  public static final int OrLogico = 97;
  public static final int Res_Byte32 = 31;
  public static final int DosPuntos = 119;
  public static final int Reste = 109;
  public static final int CierraCorchete = 118;
  public static final int Res_Bytes64 = 23;
  public static final int Resta = 125;
  public static final int CorrerALaDerecha = 100;
  public static final int Res_View = 71;
  public static final int Res_Delete = 38;
  public static final int Sume = 108;
  public static final int Res_Function = 44;
  public static final int Unit_Minutes = 83;
  public static final int Suma = 124;
  public static final int Res_Byte8 = 29;
  public static final int Unit_Years = 88;
  public static final int Cadena = 129;
  public static final int Res_Byte4 = 28;
  public static final int Res_Byte2 = 27;
  public static final int Trans_Transfer = 78;
  public static final int Res_Returns = 54;
  public static final int Res_Int64 = 8;
  public static final int NotLogico = 92;
  public static final int Unit_Ether = 80;
  public static final int AbreLlave = 114;
  public static final int Res_If = 11;
  public static final int Trans_Delgatecall = 76;
  public static final int Res_Private = 51;
  public static final int Res_Continue = 36;
  public static final int Comparacion = 95;
  public static final int Unit_Wei = 87;
  public static final int Res_True = 59;
  public static final int Res_Byte256 = 34;
  public static final int PuntoYComa = 120;
  public static final int Res_Public = 52;
  public static final int Res_Return = 53;
  public static final int MayorQue = 103;
  public static final int Asignacion = 123;
  public static final int Res_Pragma = 50;
  public static final int Res_Byte16 = 30;
  public static final int Res_Ufixed = 60;
  public static final int Res_Internal = 46;
  public static final int Res_Payable = 49;
  public static final int Res_Uint128 = 68;
  public static final int Res_Else = 12;
  public static final int NotBits = 106;
  public static final int Res_Mapping = 47;
  public static final int Res_Uint32 = 66;
  public static final int Res_Import = 45;
  public static final int Res_Bytes256 = 25;
  public static final int Res_As = 14;
  public static final int Unit_Szabo = 85;
  public static final int Res_This = 58;
  public static final int AbreCorchete = 117;
  public static final int Flotante = 91;
  public static final int Res_Int256 = 10;
  public static final int EOF = 0;
  public static final int Res_Int8 = 5;
  public static final int Res_False = 41;
  public static final int Hexadecimal = 128;
  public static final int Res_Int4 = 4;
  public static final int Numero = 131;
  public static final int Res_Int2 = 3;
  public static final int Res_Solidity = 55;
  public static final int Division = 127;
  public static final int AndBits = 104;
  public static final int Unit_Weeks = 86;
  public static final int Res_Byte64 = 32;
  public static final int AndLogico = 93;
  public static final int Unit_Finney = 81;
  public static final int Diferencia = 96;
  public static final int Res_Bytes32 = 22;
  public static final int Res_Address = 13;
  public static final int error = 1;
  public static final int Res_Bytes8 = 20;
  public static final int Res_String = 56;
  public static final int Error = 134;
  public static final int Res_Uint = 61;
  public static final int Comillas = 132;
  public static final int Potencia = 94;
  public static final int AbreParentesis = 112;
  public static final int Res_Bytes4 = 19;
  public static final int OrBits = 105;
  public static final int Res_Bytes2 = 18;
  public static final int ComentarioBloque = 89;
  public static final int Res_Int32 = 7;
  public static final int Identificador = 130;
  public static final int Res_Contract = 37;
  public static final int Res_Var = 70;
  public static final int Res_While = 72;
  public static final int Res_Uint16 = 65;
  public static final int Res_Byte = 26;
  public static final int Unit_Seconds = 84;
  public static final int Res_Byte128 = 33;
  public static final int Divida = 111;
  public static final int Res_Break = 16;
  public static final int Res_Bool = 15;
  public static final int Multiplicacion = 126;
  public static final int MayorOIgualQue = 102;
  public static final int MenorOIgualQue = 98;
  public static final int Res_From = 43;
  public static final int Interrogacion = 116;
  public static final int Res_Bytes = 17;
  public static final int Escape = 133;
  public static final int CierraParentesis = 113;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Res_Int",
  "Res_Int2",
  "Res_Int4",
  "Res_Int8",
  "Res_Int16",
  "Res_Int32",
  "Res_Int64",
  "Res_Int128",
  "Res_Int256",
  "Res_If",
  "Res_Else",
  "Res_Address",
  "Res_As",
  "Res_Bool",
  "Res_Break",
  "Res_Bytes",
  "Res_Bytes2",
  "Res_Bytes4",
  "Res_Bytes8",
  "Res_Bytes16",
  "Res_Bytes32",
  "Res_Bytes64",
  "Res_Bytes128",
  "Res_Bytes256",
  "Res_Byte",
  "Res_Byte2",
  "Res_Byte4",
  "Res_Byte8",
  "Res_Byte16",
  "Res_Byte32",
  "Res_Byte64",
  "Res_Byte128",
  "Res_Byte256",
  "Res_Constructor",
  "Res_Continue",
  "Res_Contract",
  "Res_Delete",
  "Res_Do",
  "Res_Enum",
  "Res_False",
  "Res_For",
  "Res_From",
  "Res_Function",
  "Res_Import",
  "Res_Internal",
  "Res_Mapping",
  "Res_Moddifier",
  "Res_Payable",
  "Res_Pragma",
  "Res_Private",
  "Res_Public",
  "Res_Return",
  "Res_Returns",
  "Res_Solidity",
  "Res_String",
  "Res_Struct",
  "Res_This",
  "Res_True",
  "Res_Ufixed",
  "Res_Uint",
  "Res_Uint2",
  "Res_Uint4",
  "Res_Uint8",
  "Res_Uint16",
  "Res_Uint32",
  "Res_Uint64",
  "Res_Uint128",
  "Res_Uint256",
  "Res_Var",
  "Res_View",
  "Res_While",
  "Trans_Balance",
  "Trans_Call",
  "Trans_Callcode",
  "Trans_Delgatecall",
  "Trans_Send",
  "Trans_Transfer",
  "Unit_Days",
  "Unit_Ether",
  "Unit_Finney",
  "Unit_Hours",
  "Unit_Minutes",
  "Unit_Seconds",
  "Unit_Szabo",
  "Unit_Weeks",
  "Unit_Wei",
  "Unit_Years",
  "ComentarioBloque",
  "Cientifico",
  "Flotante",
  "NotLogico",
  "AndLogico",
  "Potencia",
  "Comparacion",
  "Diferencia",
  "OrLogico",
  "MenorOIgualQue",
  "CorrerALaIzquierda",
  "CorrerALaDerecha",
  "MenorQue",
  "MayorOIgualQue",
  "MayorQue",
  "AndBits",
  "OrBits",
  "NotBits",
  "Porcentaje",
  "Sume",
  "Reste",
  "Multiplique",
  "Divida",
  "AbreParentesis",
  "CierraParentesis",
  "AbreLlave",
  "CierraLlave",
  "Interrogacion",
  "AbreCorchete",
  "CierraCorchete",
  "DosPuntos",
  "PuntoYComa",
  "Coma",
  "Punto",
  "Asignacion",
  "Suma",
  "Resta",
  "Multiplicacion",
  "Division",
  "Hexadecimal",
  "Cadena",
  "Identificador",
  "Numero",
  "Comillas",
  "Escape",
  "Error"
  };
}

